server:
  port: 12000
  servlet:
    context-path: /cam
spring:
  application:
    name: cam-authorization-server
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.3.100:3306/cam
    username: root
    password: 123456
  security:
    oauth2:
      client:
        registration:
          google-idp:
            provider: google
            client-id: ${GOOGLE_CLIENT_ID:google-client-id}
            client-secret: ${GOOGLE_CLIENT_SECRET:google-client-secret}
            scope: openid, https://www.googleapis.com/auth/userinfo.profile, https://www.googleapis.com/auth/userinfo.email
            client-name: Sign in with Google
          github-idp:
            provider: github
            client-id: ${GITHUB_CLIENT_ID:github-client-id}
            client-secret: ${GITHUB_CLIENT_SECRET:github-client-secret}
            scope: user:email, read:user
            client-name: Sign in with GitHub
        provider:
          google:
            user-name-attribute: email
          github:
            user-name-attribute: login

application:
  security:
    excludeUrls: #excludeUrls中存放白名单地址, 不需要经过授权
      - "/favicon.ico"

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml


logging:
  level:
    root: debug